import ReduxProvider from '../../redux/ReduxProvider';
import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });
import Data from './data.json';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReduxProvider Data={Data}>{children}</ReduxProvider>
      </body>
    </html>
  );
}
